version: '3.8'

services:
  attendance-bot:
    build: .
    environment:
      - SHOW_UI=false
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - .:/app
      - .env:/app/.env
    restart: unless-stopped

